//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsuStdToTaikoGui {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OsuStdToTaikoGui.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   osu!converter Std2Taiko に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   等速譜面を追加で出力する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConstantSpeed {
            get {
                return ResourceManager.GetString("ConstantSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換開始 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚠ 注意: SV が上限に到達する区間を検出しました。完全な等速を実現したい場合は 「BPM 調整を許可する」を使用して下さい。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CsClampWarnHeader {
            get {
                return ResourceManager.GetString("CsClampWarnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CsClampWarnLine {
            get {
                return ResourceManager.GetString("CsClampWarnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここに .osu をドラッグ＆ドロップ（クリックで参照） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropHint {
            get {
                return ResourceManager.GetString("DropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここにドロップして選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropNow {
            get {
                return ResourceManager.GetString("DropNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   osu!standard（Mode: 0）の譜面のみ変換できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrNotStandard {
            get {
                return ResourceManager.GetString("ErrNotStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ファイルが無効です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidInputFile {
            get {
                return ResourceManager.GetString("InvalidInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セーフモード（Aspire譜面用） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LazerSafe {
            get {
                return ResourceManager.GetString("LazerSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NG: {0} : {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogNg {
            get {
                return ResourceManager.GetString("LogNg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK: {0} -&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOk {
            get {
                return ResourceManager.GetString("LogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK (Constant speed): {0} -&gt; {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOkConstantSpeed {
            get {
                return ResourceManager.GetString("LogOkConstantSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LogOutput {
            get {
                return ResourceManager.GetString("LogOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   osu! lazer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModeLazer {
            get {
                return ResourceManager.GetString("ModeLazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   original（デバック用） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModeOriginal {
            get {
                return ResourceManager.GetString("ModeOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   osu! stable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModeStable {
            get {
                return ResourceManager.GetString("ModeStable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変換エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConvertErrorTitle {
            get {
                return ResourceManager.GetString("MsgConvertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正常に変換されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConvertSuccessBody {
            get {
                return ResourceManager.GetString("MsgConvertSuccessBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力モード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputMode {
            get {
                return ResourceManager.GetString("OutputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ℹ BPM 線を置換しました（安定化のため） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaReplaceHeader {
            get {
                return ResourceManager.GetString("SvaReplaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区間 t={0}..{1} x{2} BPM {3:0.########} → {4:0.########}（BPM 線統合={5}, SV線補完={6}） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaReplaceLine {
            get {
                return ResourceManager.GetString("SvaReplaceLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚠ 注意: BPM 調整区間に DrumRoll / Swell が多い可能性があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaRollSwellWarnHeader {
            get {
                return ResourceManager.GetString("SvaRollSwellWarnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区間 t={0}..{1} DrumRoll={2} Swell={3} Objects={4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaRollSwellWarnLine {
            get {
                return ResourceManager.GetString("SvaRollSwellWarnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BPM 調整 ＋ SV 線補正により、 DrumRoll / Swell の見た目・体感が通常とズレる場合があります（要確認）。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaRollSwellWarnNote {
            get {
                return ResourceManager.GetString("SvaRollSwellWarnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ℹ SV 上限を超える区間が無かったため BPM 調整は行われませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaSkipNote {
            get {
                return ResourceManager.GetString("SvaSkipNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///     SV線: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaWarnGreenLine {
            get {
                return ResourceManager.GetString("SvaWarnGreenLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚠ 注意: SV 演出（緑線変化）がある区間を補正しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaWarnHeader {
            get {
                return ResourceManager.GetString("SvaWarnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BPM 調整に合わせてSV 線の beatLength を倍率分スケールします。この区間の SV 演出は見た目が変わります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaWarnNote {
            get {
                return ResourceManager.GetString("SvaWarnNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区間 t={0}..{1} x{2} SV 線={3} 補完={4} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SvaWarnSegment {
            get {
                return ResourceManager.GetString("SvaWarnSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BPM 調整を許可する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UiSvaEnable {
            get {
                return ResourceManager.GetString("UiSvaEnable", resourceCulture);
            }
        }
    }
}
